export type SocialPlatform = 
  | 'facebook'
  | 'instagram'
  | 'twitter'
  | 'x'
  | 'tiktok'
  | 'linkedin'
  | 'youtube'
  | 'pinterest'
  | 'snapchat'
  | 'whatsapp'
  | 'telegram'
  | 'discord'
  | 'github'
  | 'medium'
  | 'reddit'
  | 'other';